name: vaccination

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - names : checkout
      uses : actions/checkout
    - name: make all
      run: make -f Makefile all
